/**
 * POT microcopy EN — sync mirror of `./es.ts`.
 *
 * ES is canonical. EN is a professional, conservative translation that
 * preserves POT brand voice. Translation rules followed:
 *
 *   - Venezuelan-specific regulatory / financial terms (cédula, RIF, Bs,
 *     Pago Móvil, Débito Inmediato, R4) are KEPT in Spanish — they are
 *     technical references with no English equivalent that wouldn't lose
 *     regulatory meaning.
 *   - Pure technical tokens (QR, OTP, PDF, PNG, WhatsApp, SMS, KYC, GMV,
 *     SLA, USD, SLO, CSV) are unchanged.
 *   - Brand tagline "Pagos Oportunos y Transparentes" → "Timely &
 *     Transparent Tips" (preserving the POT acronym backronym).
 *
 * Tone: neutral-to-warm; matches ES tuteo with informal "you" (no titles,
 * no formal register).
 *
 * Source of truth: keep the key shape in lockstep with `./es.ts`. The
 * `tests/catalog-completeness.spec.ts` enforces ES.keys === EN.keys.
 */

import { tpl } from '../utils/interpolate';

const microcopy = {
  worker: {
    onboarding: {
      welcomeTitle: "I'm a worker",
      welcomeBody: 'Receive tips straight to your Pago Móvil.',
      phonePrompt: "What's your phone number?",
      phoneHint: "We'll text you a code.",
      otpPrompt: 'We sent you a code',
      otpResend: 'Resend code',
      otpResendIn: tpl('Resend code in {seconds}s'),
      otpChangeNumber: 'Change number',
      cedulaPrompt: 'Your cédula',
      cedulaHint: 'So your bank can identify you.',
      cedulaTypeV: 'V',
      cedulaTypeE: 'E',
      datosPrompt: 'Your details',
      datosBody: 'As they appear on your cédula.',
      datosFirstName: 'First name',
      datosLastName: 'Last name',
      datosUploadPhoto: 'Upload photo',
      bankPrompt: 'Which bank does it go to?',
      bankHint: "This is where your tips arrive. You can change it later.",
      bankSelectPlaceholder: 'Select your bank',
      bankHolderCedula: 'Account holder cédula',
      bankHolderPhone: 'Pago Móvil phone',
      bankInfo: 'This is where tips arrive. You can change it later from My account.',
      pushTitle: 'Get notified instantly',
      pushBody: "We'll ping you the moment a tip lands.",
      termsTitle: 'Terms & conditions',
      termsSubtitle: 'Short summary. Full version at POT.app/terms.',
      termsAccept: 'I accept the terms',
      termsAcceptCheckbox: 'I accept the terms & conditions',
      qrReadyTitle: tpl("You're set, {firstName}!"),
      qrReadyBody: "This is your QR. Share it, print it, take it with you.",
      activatePush: 'Enable notifications',
      notNow: 'Not now',
      createAccount: 'Create account',
      start: 'Start',
    },
    home: {
      greeting: tpl('Hi, {firstName}'),
      reviewPrompt: 'Check it out',
      todayIncome: "Today's income",
      tipsCount: '# of tips',
      avgTicket: 'Average ticket',
      recentTips: 'Recent tips',
      viewAll: 'View all',
      shareQR: 'Share your QR',
      pendingAcceptanceOne: '1 pote waiting for your acceptance',
      pendingAcceptanceMany: tpl('{count} potes waiting for your acceptance'),
      pendingAcceptanceCta: 'Go',
    },
    qr: {
      title: 'My QR',
      share: 'Share',
      downloadPng: 'PNG',
      downloadPdf: 'Printable PDF',
      downloadPdfShort: 'PDF',
      requestSticker: 'Request physical sticker',
      requestStickerCta: 'Request physical sticker · Coming soon',
      comingSoon: 'Coming soon',
    },
    history: {
      title: 'History',
      filterToday: 'Today',
      filterWeek: 'Week',
      filterMonth: 'Month',
      filterCustom: 'Custom',
      sourceAll: 'All',
      sourcePersonal: 'Personal',
      sourcePote: 'By pote',
      groupToday: 'Today',
      groupYesterday: 'Yesterday',
      anonymous: 'Anonymous',
      empty: "You don't have any tips yet",
      emptyBody: 'Share your QR to start receiving.',
      seeMyQR: 'See my QR',
    },
    txDetail: {
      title: 'Tip received',
      validatedBy: 'Validated by R4',
      ref: 'Reference',
      date: 'Date',
      bank: 'Issuing bank',
      from: 'From',
      message: 'Message',
      relativeTime: tpl('{minutes} minutes ago'),
      viewPoT: 'View receipt (PoT)',
      reportProblem: 'Report a problem',
    },
    report: {
      title: 'Report a problem',
      sla: 'Support replies within 24h.',
      reasonNotReceived: "Didn't arrive in my bank",
      reasonWrongAmount: 'Wrong amount',
      reasonOther: 'Other',
      detailsPlaceholder: 'Tell us what happened (optional)…',
      send: 'Send report',
      sentTitle: 'Report sent',
      sentBody: "We'll review it within 24h and reply on WhatsApp.",
      sentCta: 'Done',
    },
    account: {
      title: 'My account',
      destination: 'Destination account',
      myPotes: 'My potes',
      config: 'Settings',
      notifications: 'Notifications',
      notificationsPushMaster: 'Push (master)',
      notificationsTips: 'Tips received',
      notificationsWeekly: 'Weekly summary',
      notificationsWhatsapp: 'WhatsApp',
      biometric: 'Biometrics',
      language: 'Language',
      languageEs: 'Language · Spanish',
      about: 'About POT',
      logOut: 'Log out',
      languageComingSoon: 'Coming soon',
      termsLabel: 'Terms & conditions',
      termsExternalUrl: 'https://po-t.app/terms',
      editAccountTitle: 'Edit destination account',
      editOtpWarning: "For security we'll ask for your OTP again.",
      saveChanges: 'Save changes',
    },
    push: {
      tipReceivedTitle: 'New tip',
      tipReceivedBody: tpl('You got Bs {amount} new'),
      tipReceivedViewDetail: 'View details',
    },
    state: {
      arrived: 'It arrived!',
      noConnection: 'No connection',
      noConnectionBody: "We couldn't connect. Check your internet and try again.",
      serviceDown: 'Service temporarily unavailable',
      retry: 'Retry',
    },
    recovery: {
      title: 'Recover your account',
      body: "Changed your phone number? We'll help you recover your QR and tips.",
      cedulaLabel: 'Your cédula',
      sla: "Support replies within 24h. We'll ask for a photo of your cédula to verify.",
      submit: 'Request recovery',
    },
    support: {
      title: 'Support',
      searchPlaceholder: 'Search FAQs',
      whatsapp: 'Chat on WhatsApp',
      whatsappFallbackTitle: "Don't have WhatsApp?",
      whatsappFallbackBody: "Email us at soporte@po-t.app and we'll reply within 24h.",
      whatsappFallbackEmail: 'soporte@po-t.app',
    },
    login: {
      title: 'Welcome',
      body: 'Sign in with your phone to continue.',
      newUser: "I'm new",
      changedPhone: 'I changed my phone',
      archivedTitle: 'Account archived',
      archivedBody:
        'This account has been archived. To reactivate, contact support: soporte@po-t.app',
      archivedContactCta: 'Contact support',
    },
    pote: {
      myPotesTitle: 'My potes',
      joinTitle: 'Join a pote',
      joinHeading: 'Invitation code',
      joinPrompt: 'Invitation code',
      joinHint: 'Your manager gave it to you. Format: XXX-XXXX',
      joinScanQR: 'Scan invitation QR',
      joinOrSep: 'or',
      joinAction: 'Join',
      detailTitle: tpl('Pote {name}'),
      yourRole: 'Your role',
      yourRoleWaiter: 'Waiter',
      weightLabel: tpl('Distribution weight: {pct}'),
      weeklyIncome: 'Weekly income',
      yourShare: 'Your estimated share',
      recentDistributions: 'Recent distributions',
      leavePote: 'Leave pote',
      historyTitle: 'Pote history',
      filterAll: 'All',
      filterPending: 'Pending',
      filterPaid: 'Paid',
      statusPaid: 'Paid',
      statusPending: 'Pending',
      filterTabActive: 'Active',
      filterTabPendingAccept: 'Pending acceptance',
      filterTabArchived: 'Archived',
      acceptTitle: 'Accept the pote conditions',
      acceptInvitedBy: tpl('{managerName} invited you to {poteName}'),
      acceptHowItWorksTitle: 'How it works',
      acceptHowItWorksBody:
        "When a customer tips the pote, R4 will automatically distribute your share based on the agreed rule. You receive your tip in your account instantly.",
      acceptRuleSectionTitle: 'Distribution rule',
      acceptMembersTitle: 'Pote members',
      acceptCta: 'Accept and join',
      rejectCta: 'Reject',
      acceptHelperText: 'By accepting, your name and destination account are included in the rule.',
      pushInvitedTitle: "You've been invited to a pote",
      pushInvitedBody: tpl('{managerName} invited you to {poteName}'),
      reAcceptanceBannerTitle: 'Rules updated',
      reAcceptanceBannerBody:
        'The manager changed the pote conditions. Review the changes before accepting.',
      reAcceptanceDiffTitle: 'Comparison',
      reAcceptanceDiffBefore: 'Before',
      reAcceptanceDiffAfter: 'After',
      reAcceptanceCta: 'Accept updated rules',
      reAcceptanceLeaveCta: 'Leave pote',
      reAcceptancePushTitle: 'The pote conditions changed',
      reAcceptancePushBody: tpl('{managerName} updated the rule for {poteName}'),
      demoModeNew: 'Mode: New invitation',
      demoModeReacceptance: 'Mode: Re-acceptance',
      demoModeStale: 'Mode: Expired invitation',
      staleTitle: 'Invitation no longer valid',
      staleBody:
        'The manager cancelled this invitation or archived the pote. Ask for a new one if you want to join.',
      staleCta: 'Back to My potes',
    },
  },
  commerce: {
    onboarding: {
      welcomeTitle: 'For your business',
      welcomeBody: "Receive tips for your team. Without touching your till.",
      registerCommerce: 'Register business',
      logIn: 'Log in',
      verifyTitle: 'Verify your phone',
      verifySent: tpl('We sent a code to {phone}'),
      verifyResend: 'Resend code',
      verifyResendIn: tpl('Resend code in {seconds}s'),
      verifyCta: 'Verify',
      datosTitle: 'Business details',
      datosLegalName: 'Legal name',
      datosRif: 'RIF',
      datosRifTypeJ: 'J',
      datosRifTypeG: 'G',
      datosRifTypeV: 'V',
      datosSector: 'Sector',
      datosSectorPlaceholder: 'Select a sector',
      datosBusinessType: 'Business type',
      datosBusinessTypePlaceholder: 'Select the type',
      datosEmail: 'Notification email',
      datosEmailPlaceholder: 'admin@business.com',
      datosEmailHelper: "You'll receive weekly summaries and important alerts",
      addressSearchPlaceholder: 'Search your address...',
      addressMapPreview: 'Map preview',
      addressSuggestion1: 'Av. Principal Las Mercedes, Caracas, Miranda',
      addressSuggestion2: 'CC Tolón, Las Mercedes, Caracas',
      addressSuggestion3: 'Av. Francisco de Miranda, Los Palos Grandes, Caracas',
      addressTitle: 'Fiscal address',
      addressState: 'State',
      addressCity: 'City',
      addressLine: 'Address',
      addressZip: 'ZIP code',
      poteAccountTitle: 'Pote destination account',
      poteAccountBody: 'This is where pote tips arrive to be distributed.',
      poteAccountBankLabel: 'Bank',
      poteAccountRif: 'Holder RIF',
      poteAccountPhone: 'Pago Móvil phone',
      poteAccountInfo:
        'This account is NOT your till. It only receives tips that you then distribute to the team.',
      managerTitle: 'About you',
      managerBody: 'We need to verify you as the legal manager.',
      managerCedulaTypeV: 'V',
      managerCedulaTypeE: 'E',
      managerRole: 'Your role',
      managerRoleOwner: 'Owner',
      managerRoleGm: 'General manager',
      managerRoleSupervisor: 'Supervisor',
      uploadTitle: 'Commercial registration',
      uploadHint: 'PDF or photo. Helps us verify your business in under 24h.',
      uploadDrop: 'Drop your PDF here',
      uploadOr: 'or click to select',
      uploadCamera: 'Take a photo with the camera',
      uploadSubmit: 'Upload and submit',
      pendingTitle: 'Verifying your business',
      pendingBody: "We'll get back within 24h. Meanwhile, you can create your first pote.",
      pendingCta: 'Create first pote',
      pendingBack: 'Back to home',
      success: 'Your pote is ready',
      rejectedTitle: "We couldn't verify your business",
      rejectedBody:
        "Reason: The commercial registration uploaded doesn't match the declared RIF. Verify and re-upload.",
      rejectedCta: 'Re-submit documents',
      rejectedContactSupport: 'If you have questions, email us at soporte@po-t.app',
      kycReviewWarningTitle: 'Heads up',
      kycReviewWarningBody:
        'Changes to fiscal data (RIF, legal name, address) require a new verification (24h). Your business will pause payments until approved.',
    },
    home: {
      greeting: tpl('Hi {firstName}'),
      todayIncome: "Today's income",
      kycBanner: 'KYC verification pending · ~24h',
      myPotes: 'My potes',
      createPote: 'Create pote',
      poteActive: 'Active',
      potePaused: 'Paused',
      poteMembers: tpl('{count} members'),
    },
    pote: {
      detailEdit: 'Edit',
      currentRule: 'Current rule',
      team: tpl('Team ({count})'),
      lastShifts: 'Recently closed shifts',
      closeShift: 'Close shift',
      closeShiftQ: 'Who worked today?',
      closeShiftBody: 'Select the team and adjust hours if needed.',
      closeShiftCalc: 'Calculate distribution',
      ruleSelectTitle: 'Distribution rule',
      rulePersonal: 'Personal',
      rulePersonalDesc: '100% goes to a single worker',
      ruleEqual: 'Equal',
      ruleEqualDesc: 'Everyone receives the same',
      ruleFixed: 'Fixed percentages',
      ruleFixedDesc: 'Each person with a specific %',
      ruleRole: 'By role',
      ruleRoleDesc: 'Weights based on position',
      ruleHours: 'By hours',
      ruleHoursDesc: 'Proportional to shift hours',
      rulePoints: 'By points',
      rulePointsDesc: 'Custom points system',
      rulePreview: 'Preview with dummy data',
      ruleSave: 'Save rule',
      createTitle: 'Create pote',
      createName: 'Pote name',
      createDestLabel: 'Destination account',
      createUseCommerce: 'Use business account',
      createUseOther: 'Use a different account',
      createSubmit: 'Create pote',
      multiTitle: 'My potes',
      multiAdd: 'Add',
      detailMembersLabel: tpl('Team ({count})'),
      detailPotName: tpl('Pote {name}'),
      detailQrShareShort: 'Share',
      detailQrPng: 'PNG',
      detailQrPdf: 'PDF',
      detailRuleEditShort: 'Edit',
      ruleHoursConfigTitle: 'How are hours logged?',
      ruleHoursOptionManual: 'Manual per worker',
      ruleHoursOptionPunch: 'Automatic punch in / out',
      rulePointsConfigTitle: 'Points by role',
      rulePointsRoleWaiter: 'Waiter',
      rulePointsRoleHelper: 'Helper',
      rulePointsRoleCashier: 'Cashier',
      rulePointsRoleBartender: 'Bartender',
      ruleFixedConfigTitle: 'Percentage per worker',
      ruleFixedConfigBody: 'Assign a % to each member. The total must be 100%.',
      ruleFixedTotalLabel: 'Total',
      ruleEqualConfigBody: 'No parameters. Each member receives the same fraction.',
      ruleRoleConfigBody: 'Define the weights on the Roster screen (C-15) per worker.',
      rulePersonalConfigTitle: 'Destination worker',
      rulePersonalConfigBody: 'Select who receives 100% of this pote tips.',
      lifecycleSectionTitle: 'Pote status',
      lifecycleStatusActive: 'Active',
      lifecycleStatusArchived: 'Archived',
      lifecycleDeactivateCta: 'Deactivate pote',
      lifecycleReactivateCta: 'Reactivate pote',
      lifecycleNote: "Deactivated potes don't receive new tips but keep their history.",
      reAcceptanceConfirmTitle: 'Confirm rule change',
      reAcceptanceConfirmBody: tpl(
        '{count} workers will receive a notification to re-accept the new rules. Your pote will move to "Pending acceptance" until everyone responds.',
      ),
      reAcceptanceConfirmPrimary: 'Save and notify',
      reAcceptanceConfirmSecondary: 'Cancel',
    },
    lifecycle: {
      draft: 'Draft',
      pendingAcceptance: 'Pending acceptance',
      active: 'Active',
      archived: 'Archived',
      noteDraft: 'Adjust the rule and invite workers to activate.',
      notePendingAcceptance: 'Waiting for workers to accept the conditions.',
      noteActive: 'The pote is receiving tips with the agreed rule.',
      noteArchived: 'Not receiving new tips. History preserved.',
    },
    miCobroPot: {
      title: 'My POT charge',
      period: 'May 2026',
      grossLabel: 'Gross charged',
      feeLabel: 'POT fee',
      netLabel: 'Net distributed',
      txCounterLabel: 'Transactions',
      workersCounterLabel: 'Active workers',
      detailCta: 'View transaction detail',
      ctaFromDetail: 'My POT charge',
      footnote: 'The POT fee covers R4 processing + multi-beneficiary dispersion.',
    },
    roster: {
      title: tpl('Team · {venue}'),
      search: 'Search person',
      add: 'Add person',
      active: 'Active',
      paused: 'Paused',
      invite: 'Invite your team',
      invitePhone: 'Phone',
      inviteRole: 'Role',
      inviteWeight: 'Weight (%)',
      inviteWeightPlaceholder: '12',
      inviteRoleWaiter: 'Waiter',
      inviteRoleBartender: 'Bartender',
      inviteRoleHost: 'Host',
      inviteRoleOther: 'Other',
      inviteWhatsapp: 'Send invitation',
      inviteWhatsappTemplate: tpl(
        "Hi! I'm inviting you to the {venue} pote. Join with code {code} on POT.",
      ),
      whatsappMessageLabel: 'WhatsApp message:',
      whatsappMessageInvite:
        '"Hi! I\'m inviting you to the La Brisa pote. Join with code ABC-1234 on POT."',
      maxHint: 'Up to 30 workers per pote · POC has no real limit',
      staffViewTitle: 'Staff view',
      staffViewBody: tpl('This is how {firstName} sees their pote'),
      staffViewClose: 'Close',
      staffViewRoleLabel: tpl('{role} · {pct} of the pote'),
      staffViewWeek: 'Week',
      staffViewShare: 'Your share',
      staffViewPrivacy:
        "Each member sees their own role, weight, and estimate. They never see other members' data.",
    },
    distribution: {
      previewTitle: 'Distribution preview',
      shiftTotal: 'Shift total',
      shiftPeople: tpl('{count} people'),
      hoursLabel: tpl('{count} hours'),
      confirmPay: 'Confirm and start paying',
      executeTitle: 'Execute payments',
      executeInstructions:
        'Make the Pago Móvil from your banking app. Then mark as paid here.',
      paid: 'Paid',
      markPaid: 'Mark as paid',
      confirmIndividual: 'Confirm payment',
      confirmPaid: 'Confirm paid',
      copyAll: 'Copy all',
      refLabel: 'Pago Móvil reference',
      detailTitle: tpl('Shift · {date}'),
      detailRuleApplied: 'Rule applied',
      detailSnapshotSaved: 'Snapshot saved',
      detailHistoryTitle: 'Distributions',
      detailMembersCount: tpl('{count} members'),
      exportPdf: 'Export PDF',
    },
    reports: {
      inflowsTitle: tpl('Inflows · {venue}'),
      distributionsTitle: 'Distributions',
      exportTitle: 'Export CSV',
      exportRange: 'Date range',
      exportPotes: 'Potes',
      exportPotesAll: 'All',
      exportFields: 'Fields',
      exportFieldDate: 'Date',
      exportFieldAmount: 'Amount',
      exportFieldBank: 'Issuing bank',
      exportFieldRef: 'R4 reference',
      exportFieldWorker: 'Worker',
      exportFieldPote: 'Pote',
      generate: 'Generate CSV',
    },
    config: {
      title: 'Settings',
      dataSection: 'Business details',
      accountSection: 'Destination account',
      deleteCommerce: 'Delete business',
      editLegalName: 'Edit legal name',
      editRif: 'Edit RIF',
      editAddress: 'Edit address',
      changeBank: 'Change bank (re-OTP)',
      changePagoMovil: 'Change Pago Móvil (re-OTP)',
      kycRejectedTitle: "We couldn't verify your business",
      kycRejectedBody:
        "Reason: the commercial registration uploaded doesn't match the declared RIF. Verify and re-upload.",
      kycResubmit: 'Re-submit documents',
    },
  },
  consumer: {
    tipping: {
      cta: tpl('Tip {firstName}'),
      amountTitle: 'Amount',
      amountOther: 'Other amount',
      sharedPotePrompt: 'Shared pote? Pick a %',
      customAmountTitle: 'Other amount',
      customAmountLabel: 'Tip',
      customAmountSwitchBs: 'Bs',
      customAmountSwitchUsd: 'USD',
      messageTitle: 'Anything else?',
      messageBody: tpl('A short message for {firstName} (optional).'),
      messagePlaceholder: 'Great service 💚',
      messageSkip: 'Skip',
      confirmTitle: 'Confirm',
      confirmTo: 'To',
      confirmAmount: 'Amount',
      confirmMessage: 'Message',
      confirmMethod: 'Method',
      confirmMethodValue: 'Débito Inmediato',
      confirmDisclaimer: "This tip is voluntary and on top of the 10% service charge.",
      confirmTipLabel: 'Tip for',
      confirmTipAmountLabel: 'Tip',
      confirmTotalLabel: 'Total to pay',
      confirmServiceDisclosure: 'The total includes POT gateway service',
      confirmMessageLabel: 'Your message',
      payCtaTotal: tpl('Pay {amount}'),
      payCta: 'Pay with Débito Inmediato',
      bankPickerTitle: 'Your bank',
      bankPickerBody: 'Select the bank issuing the payment.',
      debitoTitle: 'Débito Inmediato',
      debitoIntro: 'Generate the key in your bank and paste it here.',
      debitoStep1: 'Open your banking app',
      debitoStep2: 'Generate the 8-digit key',
      debitoStep3: 'Come back and paste it below',
      debitoKeyLabel: '8-digit key',
      debitoSafety: '🔒 The key expires in 2 minutes. Your money goes straight to Pago Móvil.',
      debitoConfirm: 'Confirm payment',
      processingTitle: 'Processing your tip',
      processingBody: 'This takes less than 10 seconds.',
      processingStep1: 'Validating with your bank',
      processingStep2: 'Processing dispersion',
      processingStep3: 'Generating receipt',
      successTitle: 'Done!',
      successBody: tpl('{firstName} just got your tip'),
      successTip: 'Tip',
      successRef: 'Reference',
      successDate: 'Date',
      successValidatedBy: 'Validated by',
      successWhatsapp: 'Get receipt on WhatsApp',
      successShare: 'Share',
      successDone: 'Done',
      potPublicReceived: 'Received',
      potPublicAnonRef: 'Anonymized reference',
      potPublicShareBody: 'Each PoT is a verifiable receipt. Share it wherever you want.',
      potPublicShare: 'Share PoT',
      errorTitle: "We couldn't process",
      errorBody: "Your bank didn't accept the 8-digit key. It usually expires after 2 minutes.",
      errorOtherBank: 'Use another bank',
      qrInvalidTitle: 'This QR no longer works',
      qrInvalidBody:
        'The worker may have deactivated or updated their QR. Ask for a new one at the venue.',
      qrInvalidBack: 'Back',
      qrInvalidClose: 'Close',
      feeAboutLink: 'What is POT?',
      feeAboutTitle: 'What is POT?',
      feeAboutBody:
        "POT is the gateway connecting your payment to the worker's bank. The service covers R4 processing and instant dispersion. The worker receives the full tip in their account.",
      feeAboutClose: 'Done',
    },
  },
  admin: {
    login: {
      title: 'POT · Admin',
      subtitle: 'Solariis team only',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      twoFaLabel: '2FA code',
      enter: 'Sign in',
      footer: 'Restricted access. All activity is audited.',
    },
    dashboard: {
      title: 'Dashboard',
      brandLine: 'Admin · POT',
      txProcessed: 'TX processed (today)',
      gmv: 'GMV (USD)',
      activeWorkers: 'Active workers',
      verifiedCommerces: 'Verified businesses',
      potFeeRevenue: 'POT fee revenue (today)',
      potFeeRevenueDeltaPositive: tpl('+{pct}% vs yesterday'),
      txPerHour: 'TX per hour · last 24h',
      successRate: 'Success rate',
      r4Latency: 'Average R4 latency',
      r4LatencyValue: tpl('Average R4 latency: {latency}'),
      alertsActive: 'Active alerts',
      alerts: 'alerts',
      alertsBadge: tpl('{count} alerts'),
      alertBlockedCompliance: '1 business blocked by compliance · 2h',
      alertPotPending: '4 PoT with pending regeneration',
      alertReconcilDelta: 'R4 reconciliation discrepancy · Bs 12.50',
      alertActionResolve: 'Resolve →',
    },
    lookup: {
      usersTitle: 'Lookup users',
      usersBody: 'Search workers by phone, cédula, or reference.',
      usersPlaceholder: 'phone, cédula, or ref ····',
      colWorker: 'Worker',
      colCedula: 'Cédula',
      colPhone: 'Phone',
      colStatus: 'Status',
      colTipsCount: '# tips',
      statusActive: 'Active',
      statusPaused: 'Paused',
      txTitle: 'Lookup transactions',
      txColRef: 'Ref',
      txColDate: 'Date',
      txColFrom: 'From',
      txColTo: 'To',
      txColAmount: 'Amount',
      txColStatus: 'Status',
      txStatusOk: 'OK',
      txStatusFailed: 'Failed',
      txPaginationLabel: tpl('{count} of {total} tx'),
      filters: 'Filters',
    },
    userDetail: {
      title: 'Admin · Worker',
      statusActive: 'Active',
      tipsTotal: 'Total tips',
      gmv: 'GMV',
      since: 'Since',
      actionsLabel: 'Actions',
      pause: 'Pause',
      changeAccount: 'Change account',
      resetOtp: 'Reset OTP',
      lastTransactions: 'Recent transactions',
      viewActivityLog: 'View activity log →',
    },
    txDetail: {
      brandLine: 'Transaction',
      statusLabel: 'Status',
      statusValidated: 'Validated by R4',
      latencyLabel: tpl('Latency: {latency}'),
      auditTrail: 'Audit trail',
      auditStarted: 'Started',
      auditValidated: 'Validated by issuing bank',
      auditWebhook: 'R4 webhook',
      auditDispersion: 'Dispersion complete',
      auditPotGenerated: 'PoT generated',
      r4Payload: 'R4 webhook payload',
      regeneratePoT: 'Regenerate PoT',
      openPublic: 'Open public PoT',
    },
    kyc: {
      queueTitle: 'Verification queue',
      queueBody: tpl('{count} businesses awaiting KYC'),
      queueWaitingLabel: tpl('{rif} · waiting {waiting}'),
      priorityHigh: 'high',
      priorityMedium: 'medium',
      priorityLow: 'low',
      sla: 'SLA < 24h',
      reviewVerify: 'Verify',
      reviewReject: 'Reject (reason required)',
      declaredData: 'Declared data',
      declaredLegalName: 'Legal name',
      declaredRif: 'RIF',
      declaredSector: 'Sector',
      declaredAddress: 'Address',
      declaredResponsible: 'Responsible',
      declaredDestAccount: 'Destination account',
      docPreview: 'Commercial registration',
    },
    reconciliation: {
      title: 'R4 reconciliation',
      subtitle: 'Daily · auto-runs 00:30 UTC',
      colDay: 'Day',
      potCol: 'POT',
      r4Col: 'R4',
      deltaCol: 'Δ',
      colStatus: 'Status',
      statusOk: 'OK',
      statusOpen: 'Open',
      investigate: 'Investigate',
      resolve: 'Resolve',
      openCount: tpl('{count} open'),
      openBadge: tpl('{count} open'),
      resolveReasonTitle: 'Resolution reason',
      resolveReasonHint: 'Audit trail — required field.',
      resolveReasonPlaceholder: 'Briefly describe how the discrepancy was resolved…',
      resolveReasonPreset1: 'Manual adjustment in R4',
      resolveReasonPreset2: 'Duplicate tx — corrected',
      resolveReasonPreset3: 'FX rate difference',
      resolveReasonPreset4: 'Webhook reprocessed',
      resolveReasonSubmit: 'Mark resolved',
      resolveReasonCancel: 'Cancel',
    },
    health: {
      title: 'Logs / Health',
      r4Operational: 'R4 operational',
      pushOk: 'Push OK',
      webhooks24h: 'R4 webhooks (24h)',
      apiErrors24h: 'API errors (24h)',
      pushDeliveryRate: 'Push delivery rate',
      recentActivity: 'Recent activity',
      withinSlo: 'within SLO',
      attention: 'attention',
      filtersLabel: 'Filters',
      clearFilters: 'Clear filters',
      filterChipSource: 'R4 webhook',
      filterChipStatus: 'Errors only',
    },
  },
  shared: {
    common: {
      yes: 'Yes',
      no: 'No',
      cancel: 'Cancel',
      confirm: 'Confirm',
      retry: 'Retry',
      back: 'Back',
      next: 'Next',
      continue: 'Continue',
      skip: 'Skip',
      save: 'Save',
      done: 'Done',
      share: 'Share',
      download: 'Download',
      edit: 'Edit',
      delete: 'Delete',
      close: 'Close',
      search: 'Search',
      stepOf: ({ current, total }: { current: number; total: number }) =>
        `Step ${current} of ${total}`,
    },
    errors: {
      generic: 'Something went wrong',
      retry: 'Try again',
      network: 'No connection. Try again.',
      r4Unavailable: 'Service temporarily unavailable',
      invalidOtp: "The code doesn't match",
      badKey: 'Invalid key',
      expired: 'The key expired',
      noFunds: 'Insufficient funds',
    },
    money: {
      bs: 'Bs',
      usd: 'USD',
      bsApprox: (bs: string, usd: string) => `Bs ${bs} · ≈ ${usd} USD`,
    },
    splash: {
      brandTag: 'Timely & Transparent Tips',
      brandTagCommerce: 'POT · Business',
    },
    identity: {
      entityType: {
        labelDestino: 'Payment destination',
        natural: 'Natural',
        juridico: 'Legal entity',
      },
      prefixes: {
        natural: {
          V: 'V - Venezuelan',
          E: 'E - Foreigner',
          P: 'P - Passport',
        },
        juridico: {
          J: 'J - Private legal entity',
          V: 'V - Natural with RIF',
          E: 'E - Foreign with RIF',
          G: 'G - Government',
          C: 'C - Community councils',
        },
      },
      prefixSelectorAria: 'Select identity prefix',
      fieldLabels: {
        cedula: 'Cédula',
        rif: 'RIF',
      },
      placeholders: {
        cedula: '12.345.678',
        rif: '12345678-9',
      },
    },
    brand: {
      tagline: 'Timely & Transparent Tips',
    },
    transversales: {
      pushPrePrimingTitle: 'Notify you?',
      pushPrePrimingBody:
        "We're about to ask permission to notify you when a tip arrives. Turn it off whenever you want.",
      pushPrePrimingYes: 'Yes, notify me',
      cameraPrePrimingTitle: 'Allow camera',
      cameraPrePrimingBody:
        "To scan the venue QR. We only use it when scanning, never in the background.",
      cameraPrePrimingYes: 'Allow camera',
      updateTitle: 'There is a new version',
      updateBody: 'Update POT to keep receiving tips. Takes less than a minute.',
      updateCta: 'Update now',
      maintenanceTitle: 'Were improving POT',
      maintenanceBody: "We'll let you know when it's done. You won't miss a single tip.",
      maintenanceEta: 'Back in ~15 minutes',
      pushPrePrimingBodyAlt:
        "We're about to ask permission to notify you when a tip arrives. You can turn them off whenever you want.",
      cameraPrePrimingTitleAlt: 'Allow camera',
      cameraPrePrimingYesAlt: 'Allow camera',
      updateBodyAlt: 'Update POT to keep receiving tips. Takes less than a minute.',
      errorModalTitle: 'Something went wrong',
      errorModalBody: "We couldn't complete your request. Try again in a few seconds.",
    },
  },
} as const;

export default microcopy;
export { microcopy };
