/**
 * POT microcopy ES-VE — canónico v2.3 (mirror of `pot-poc/lib/microcopy.ts`).
 *
 * REGLA CRÍTICA: todo string visible al usuario en pantallas DEBE
 * importar de este módulo (o del paquete `@solariis-com/pot-microcopy`).
 * Strings inline en JSX están PROHIBIDOS (NFR-MICROCOPY-01).
 *
 * Source of truth: `solariis-com/pot-poc/lib/microcopy.ts`. This file is a
 * structural mirror — keep strings identical, keep keys in the same shape.
 *
 * Tono:
 * - Venezolano coloquial pero claro
 * - Tuteo (no "usted")
 * - Sin spanglish (excepto técnicos: QR, WhatsApp)
 * - Sin formalismo excesivo
 * - Caracteres especiales correctos (acentos, ñ, apóstrofo)
 */

import { tpl } from '../utils/interpolate';

const microcopy = {
  worker: {
    onboarding: {
      welcomeTitle: 'Soy trabajador',
      welcomeBody: 'Recibí propinas directo a tu Pago Móvil.',
      phonePrompt: '¿Cuál es tu número?',
      phoneHint: 'Te enviamos un código por SMS.',
      otpPrompt: 'Te enviamos un código',
      otpResend: 'Reenviar código',
      otpResendIn: tpl('Reenviar código en {seconds}s'),
      otpChangeNumber: 'Cambiar número',
      cedulaPrompt: 'Tu cédula',
      cedulaHint: 'Para identificarte ante el banco.',
      cedulaTypeV: 'V',
      cedulaTypeE: 'E',
      datosPrompt: 'Tus datos',
      datosBody: 'Como aparecen en tu cédula.',
      datosFirstName: 'Nombre',
      datosLastName: 'Apellido',
      datosUploadPhoto: 'Subir foto',
      bankPrompt: '¿A qué banco te llega?',
      bankHint: 'Aquí van tus propinas. Puedes cambiarlo después.',
      bankSelectPlaceholder: 'Selecciona tu banco',
      bankHolderCedula: 'Cédula del titular',
      bankHolderPhone: 'Teléfono Pago Móvil',
      bankInfo: 'Aquí te llegan las propinas. Lo puedes cambiar luego desde Mi cuenta.',
      pushTitle: 'Entérate al instante',
      pushBody: 'Te avisamos apenas recibís una propina.',
      termsTitle: 'Términos y condiciones',
      termsSubtitle: 'Resumen breve. Versión completa en POT.app/terms.',
      termsAccept: 'Acepto los términos',
      termsAcceptCheckbox: 'Acepto los términos y condiciones',
      qrReadyTitle: tpl('¡Listo, {firstName}!'),
      qrReadyBody: 'Este es tu QR. Compartilo, imprimilo, llevátelo contigo.',
      activatePush: 'Activar notificaciones',
      notNow: 'Ahora no',
      createAccount: 'Crear cuenta',
      start: 'Empezar',
    },
    home: {
      greeting: tpl('Hola, {firstName}'),
      reviewPrompt: 'Echale ojo',
      // TKT-2026-0926/0927 — subtitle shown under the greeting on the
      // mobile W-10 Home. POC mockup uses this exact copy.
      reviewSubtitle: 'Revisá tus propinas de hoy',
      todayIncome: 'Ingresos hoy',
      tipsCount: '# de propinas',
      avgTicket: 'Ticket promedio',
      // TKT-2026-0927 — mobile W-10 EarningsCard hero label.
      totalEarnings: 'Ganancias totales',
      recentTips: 'Últimas propinas',
      // TKT-2026-0927 — Mobile W-10 "Historial reciente" section header.
      recentHistoryTitle: 'Historial reciente',
      viewAll: 'Ver todo',
      shareQR: 'Compartí tu QR',
      // TKT-2026-0927 — Mobile W-10 PendingInviteBanner title.
      pendingInviteTitle: 'Te invitaron a un pote',
      pendingAcceptanceOne: '1 pote esperando tu aceptación',
      pendingAcceptanceMany: tpl('{count} potes esperando tu aceptación'),
      pendingAcceptanceCta: 'Ir',
    },
    qr: {
      title: 'Mi QR',
      share: 'Compartir',
      downloadPng: 'PNG',
      downloadPdf: 'PDF imprimible',
      downloadPdfShort: 'PDF',
      requestSticker: 'Pedir sticker físico',
      requestStickerCta: 'Pedir sticker físico · Próximamente',
      comingSoon: 'Próximamente',
    },
    history: {
      title: 'Historial',
      filterToday: 'Hoy',
      filterWeek: 'Semana',
      filterMonth: 'Mes',
      filterCustom: 'Personalizado',
      sourceAll: 'Todas',
      sourcePersonal: 'Personales',
      sourcePote: 'Por pote',
      groupToday: 'Hoy',
      groupYesterday: 'Ayer',
      anonymous: 'Anónimo',
      empty: 'Aún no tenés propinas',
      emptyBody: 'Compartí tu QR para empezar a recibir.',
      seeMyQR: 'Ver mi QR',
    },
    txDetail: {
      title: 'Propina recibida',
      validatedBy: 'Validado por R4',
      ref: 'Referencia',
      date: 'Fecha',
      bank: 'Banco emisor',
      from: 'De',
      message: 'Mensaje',
      relativeTime: tpl('Hace {minutes} minutos'),
      viewPoT: 'Ver comprobante (PoT)',
      reportProblem: 'Reportar problema',
    },
    report: {
      title: 'Reportar problema',
      sla: 'Soporte responde en 24h.',
      reasonNotReceived: 'No recibí en mi banco',
      reasonWrongAmount: 'Monto incorrecto',
      reasonOther: 'Otro',
      detailsPlaceholder: 'Contanos qué pasó (opcional)…',
      send: 'Enviar reporte',
      sentTitle: 'Reporte enviado',
      sentBody: 'Lo revisamos en 24h y te respondemos por WhatsApp.',
      sentCta: 'Listo',
    },
    account: {
      title: 'Mi cuenta',
      destination: 'Cuenta destino',
      myPotes: 'Mis potes',
      config: 'Configuración',
      notifications: 'Notificaciones',
      notificationsPushMaster: 'Push (master)',
      notificationsTips: 'Propinas recibidas',
      notificationsWeekly: 'Resumen semanal',
      notificationsWhatsapp: 'WhatsApp',
      biometric: 'Biometría',
      language: 'Idioma',
      languageEs: 'Idioma · Español',
      about: 'Sobre POT',
      logOut: 'Cerrar sesión',
      languageComingSoon: 'Próximamente',
      termsLabel: 'Términos y condiciones',
      termsExternalUrl: 'https://po-t.app/terms',
      editAccountTitle: 'Editar cuenta destino',
      editOtpWarning: 'Por seguridad te pediremos tu OTP de nuevo.',
      saveChanges: 'Guardar cambios',
    },
    push: {
      tipReceivedTitle: 'Llegó una propina',
      tipReceivedBody: tpl('Tenés Bs {amount} nuevos'),
      tipReceivedViewDetail: 'Ver detalle',
    },
    state: {
      arrived: '¡Llegó!',
      noConnection: 'Sin conexión',
      noConnectionBody: 'No pudimos conectar. Verificá tu internet y volvé a intentar.',
      serviceDown: 'Servicio temporalmente no disponible',
      retry: 'Reintentar',
    },
    recovery: {
      title: 'Recupera tu cuenta',
      body: 'Si cambiaste de número, te ayudamos a recuperar tu QR y propinas.',
      cedulaLabel: 'Tu cédula',
      sla: 'Soporte responde en 24h. Te pediremos foto de cédula para verificar.',
      submit: 'Solicitar recuperación',
    },
    support: {
      title: 'Soporte',
      searchPlaceholder: 'Buscar en FAQs',
      whatsapp: 'Chatear por WhatsApp',
      whatsappFallbackTitle: '¿No tenés WhatsApp?',
      whatsappFallbackBody: 'Escribinos a soporte@po-t.app y te respondemos en 24h.',
      whatsappFallbackEmail: 'soporte@po-t.app',
    },
    login: {
      title: 'Bienvenida',
      body: 'Ingresa con tu teléfono para continuar.',
      newUser: 'Soy nuevo',
      changedPhone: 'Cambié de teléfono',
      archivedTitle: 'Cuenta archivada',
      archivedBody:
        'Esta cuenta fue archivada. Para reactivarla, contactá soporte: soporte@po-t.app',
      archivedContactCta: 'Contactar soporte',
    },
    pote: {
      myPotesTitle: 'Mis potes',
      // TKT-2026-0927 — W-30 Mis potes empty-state copy.
      myPotesEmptyActive: 'Aún no tenés potes activos.',
      // TKT-2026-0927 — W-14 Pote detail "Configure" CTA.
      configureCta: 'Configurar pote',
      // TKT-2026-0927 — W-16 Pote config screen title.
      editTitle: 'Editar pote',
      // TKT-2026-0927 — W-30 short "+ Crear" CTA used in the section
      // header beside Mis potes (full text "Crear pote" stays on the
      // primary CTA elsewhere).
      createShort: '+ Crear',
      joinTitle: 'Unirme a pote',
      joinHeading: 'Código de invitación',
      joinPrompt: 'Código de invitación',
      joinHint: 'Tu gerente te lo dio. Formato: XXX-XXXX',
      joinScanQR: 'Escanear QR de invitación',
      joinOrSep: 'o',
      joinAction: 'Unirme',
      detailTitle: tpl('Pote {name}'),
      yourRole: 'Tu rol',
      yourRoleWaiter: 'Mesero',
      weightLabel: tpl('Peso de distribución: {pct}'),
      weeklyIncome: 'Ingresos semana',
      yourShare: 'Tu parte estimada',
      recentDistributions: 'Distribuciones recientes',
      leavePote: 'Salir del pote',
      historyTitle: 'Historial del pote',
      filterAll: 'Todas',
      filterPending: 'Pendientes',
      filterPaid: 'Pagadas',
      statusPaid: 'Pagada',
      statusPending: 'Pendiente',
      filterTabActive: 'Activos',
      filterTabPendingAccept: 'Pendientes de aceptar',
      filterTabArchived: 'Archivados',
      acceptTitle: 'Acepta las condiciones del pote',
      acceptInvitedBy: tpl('{managerName} te invitó a {poteName}'),
      acceptHowItWorksTitle: 'Cómo funciona',
      acceptHowItWorksBody:
        'Cuando un cliente deje propina al pote, R4 distribuirá automáticamente tu parte según la regla acordada. Recibís tu propina en tu cuenta al instante.',
      acceptRuleSectionTitle: 'Regla de distribución',
      acceptMembersTitle: 'Integrantes del pote',
      acceptCta: 'Aceptar y unirme',
      rejectCta: 'Rechazar',
      acceptHelperText: 'Al aceptar, tu nombre y cuenta destino se incluyen en la regla.',
      pushInvitedTitle: 'Te invitaron a un pote',
      pushInvitedBody: tpl('{managerName} te invitó a {poteName}'),
      reAcceptanceBannerTitle: 'Reglas actualizadas',
      reAcceptanceBannerBody:
        'El manager cambió las condiciones del pote. Revisá los cambios antes de aceptar.',
      reAcceptanceDiffTitle: 'Comparación',
      reAcceptanceDiffBefore: 'Antes',
      reAcceptanceDiffAfter: 'Ahora',
      reAcceptanceCta: 'Aceptar reglas actualizadas',
      reAcceptanceLeaveCta: 'Salir del pote',
      reAcceptancePushTitle: 'Las condiciones del pote cambiaron',
      reAcceptancePushBody: tpl('{managerName} actualizó la regla de {poteName}'),
      demoModeNew: 'Modo: Nueva invitación',
      demoModeReacceptance: 'Modo: Re-aceptación',
      demoModeStale: 'Modo: Invitación expirada',
      staleTitle: 'Invitación ya no válida',
      staleBody:
        'El manager canceló esta invitación o archivó el pote. Pedile uno nuevo si querés unirte.',
      staleCta: 'Volver a Mis potes',
    },
  },
  commerce: {
    onboarding: {
      welcomeTitle: 'Para tu negocio',
      welcomeBody: 'Recibe propinas para tu equipo. Sin que toquen tu caja.',
      registerCommerce: 'Registrar comercio',
      logIn: 'Iniciar sesión',
      verifyTitle: 'Verifica tu teléfono',
      verifySent: tpl('Enviamos código al {phone}'),
      verifyResend: 'Reenviar código',
      verifyResendIn: tpl('Reenviar código en {seconds}s'),
      verifyCta: 'Verificar',
      datosTitle: 'Datos del comercio',
      datosLegalName: 'Razón social',
      datosRif: 'RIF',
      datosRifTypeJ: 'J',
      datosRifTypeG: 'G',
      datosRifTypeV: 'V',
      datosSector: 'Sector',
      datosSectorPlaceholder: 'Selecciona un sector',
      datosBusinessType: 'Tipo de comercio',
      datosBusinessTypePlaceholder: 'Selecciona el tipo',
      datosEmail: 'Email para notificaciones',
      datosEmailPlaceholder: 'admin@comercio.com',
      datosEmailHelper: 'Recibirás resúmenes semanales y alertas importantes',
      addressSearchPlaceholder: 'Busca tu dirección...',
      addressMapPreview: 'Vista previa en mapa',
      addressSuggestion1: 'Av. Principal Las Mercedes, Caracas, Miranda',
      addressSuggestion2: 'CC Tolón, Las Mercedes, Caracas',
      addressSuggestion3: 'Av. Francisco de Miranda, Los Palos Grandes, Caracas',
      addressTitle: 'Dirección fiscal',
      addressState: 'Estado',
      addressCity: 'Ciudad',
      addressLine: 'Dirección',
      addressZip: 'Código postal',
      poteAccountTitle: 'Cuenta destino del pote',
      poteAccountBody: 'Aquí entran las propinas del pote para distribuir.',
      poteAccountBankLabel: 'Banco',
      poteAccountRif: 'RIF titular',
      poteAccountPhone: 'Teléfono Pago Móvil',
      poteAccountInfo:
        'Esta cuenta NO es tu caja. Solo recibe las propinas que luego repartes al equipo.',
      managerTitle: 'Sobre ti',
      managerBody: 'Necesitamos verificarte como responsable legal.',
      managerCedulaTypeV: 'V',
      managerCedulaTypeE: 'E',
      managerRole: 'Tu rol',
      managerRoleOwner: 'Dueño',
      managerRoleGm: 'Gerente',
      managerRoleSupervisor: 'Encargado',
      uploadTitle: 'Registro mercantil',
      uploadHint: 'PDF o foto. Ayuda a verificar tu comercio en menos de 24h.',
      uploadDrop: 'Arrastra aquí tu PDF',
      uploadOr: 'o haz clic para seleccionar',
      uploadCamera: 'Tomar foto con la cámara',
      uploadSubmit: 'Subir y enviar',
      pendingTitle: 'Estamos verificando tu comercio',
      pendingBody: 'Te avisamos en menos de 24h. Mientras tanto, ya podés crear tu primer pote.',
      pendingCta: 'Crear primer pote',
      pendingBack: 'Volver al inicio',
      success: 'Tu pote está listo',
      rejectedTitle: 'No pudimos verificar tu comercio',
      rejectedBody:
        'Razón: El registro mercantil subido no coincide con el RIF declarado. Verifica y vuelve a subir.',
      rejectedCta: 'Volver a enviar documentos',
      rejectedContactSupport: 'Si tenés dudas, escribinos a soporte@po-t.app',
      kycReviewWarningTitle: 'Atención',
      kycReviewWarningBody:
        'Cambios en datos fiscales (RIF, razón social, dirección) requieren verificación nueva (24h). Tu comercio pausará pagos hasta aprobar.',
    },
    home: {
      greeting: tpl('Hola {firstName}'),
      todayIncome: 'Ingresos hoy',
      kycBanner: 'Verificación KYC pendiente · ~24h',
      myPotes: 'Mis potes',
      createPote: 'Crear pote',
      poteActive: 'Activo',
      potePaused: 'Pausado',
      poteMembers: tpl('{count} miembros'),
    },
    pote: {
      detailEdit: 'Editar',
      currentRule: 'Regla actual',
      team: tpl('Equipo ({count})'),
      lastShifts: 'Últimos turnos cerrados',
      closeShift: 'Cerrar turno',
      closeShiftQ: '¿Quién trabajó hoy?',
      closeShiftBody: 'Selecciona el equipo y ajusta horas si aplica.',
      closeShiftCalc: 'Calcular distribución',
      ruleSelectTitle: 'Regla de distribución',
      rulePersonal: 'Personal',
      rulePersonalDesc: '100% va a un solo trabajador',
      ruleEqual: 'Igualitaria',
      ruleEqualDesc: 'Todos reciben lo mismo',
      ruleFixed: 'Porcentajes fijos',
      ruleFixedDesc: 'Cada persona con un % específico',
      ruleRole: 'Por rol',
      ruleRoleDesc: 'Pesos según el cargo',
      ruleHours: 'Por horas',
      ruleHoursDesc: 'Proporcional a las horas del turno',
      rulePoints: 'Por puntos',
      rulePointsDesc: 'Sistema de puntos personalizado',
      rulePreview: 'Preview con datos dummy',
      ruleSave: 'Guardar regla',
      createTitle: 'Crear pote',
      createName: 'Nombre del pote',
      createDestLabel: 'Cuenta destino',
      createUseCommerce: 'Usar cuenta del comercio',
      createUseOther: 'Usar una cuenta distinta',
      createSubmit: 'Crear pote',
      multiTitle: 'Mis potes',
      multiAdd: 'Añadir',
      detailMembersLabel: tpl('Equipo ({count})'),
      detailPotName: tpl('Pote {name}'),
      detailQrShareShort: 'Compartir',
      detailQrPng: 'PNG',
      detailQrPdf: 'PDF',
      detailRuleEditShort: 'Editar',
      ruleHoursConfigTitle: '¿Cómo se registran las horas?',
      ruleHoursOptionManual: 'Manual por trabajador',
      ruleHoursOptionPunch: 'Punch in / out automático',
      rulePointsConfigTitle: 'Puntos por rol',
      rulePointsRoleWaiter: 'Mesero',
      rulePointsRoleHelper: 'Ayudante',
      rulePointsRoleCashier: 'Cajero',
      rulePointsRoleBartender: 'Bartender',
      ruleFixedConfigTitle: 'Porcentaje por trabajador',
      ruleFixedConfigBody: 'Asigna un % a cada integrante. La suma debe ser 100%.',
      ruleFixedTotalLabel: 'Total',
      ruleEqualConfigBody: 'Sin parámetros. Cada integrante recibe la misma fracción.',
      ruleRoleConfigBody: 'Define los pesos en la pantalla de Roster (C-15) por cada trabajador.',
      rulePersonalConfigTitle: 'Trabajador destino',
      rulePersonalConfigBody: 'Selecciona quién recibe el 100% de las propinas de este pote.',
      lifecycleSectionTitle: 'Estado del pote',
      lifecycleStatusActive: 'Activo',
      lifecycleStatusArchived: 'Archivado',
      lifecycleDeactivateCta: 'Desactivar pote',
      lifecycleReactivateCta: 'Reactivar pote',
      lifecycleNote:
        'Los potes desactivados no reciben propinas nuevas pero conservan el historial.',
      reAcceptanceConfirmTitle: 'Confirmar cambio de regla',
      reAcceptanceConfirmBody: tpl(
        '{count} workers van a recibir una notificación para re-aceptar las nuevas reglas. Tu pote pasará a "Esperando aceptación" hasta que todos respondan.',
      ),
      reAcceptanceConfirmPrimary: 'Guardar y notificar',
      reAcceptanceConfirmSecondary: 'Cancelar',
    },
    lifecycle: {
      draft: 'Borrador',
      pendingAcceptance: 'Esperando aceptación',
      active: 'Activo',
      archived: 'Archivado',
      noteDraft: 'Ajusta la regla e invita workers para activar.',
      notePendingAcceptance: 'Esperando que los workers acepten las condiciones.',
      noteActive: 'El pote está recibiendo propinas con la regla acordada.',
      noteArchived: 'No recibe propinas nuevas. Historial preservado.',
    },
    miCobroPot: {
      title: 'Mi cobro POT',
      period: 'Mayo 2026',
      grossLabel: 'Bruto cobrado',
      feeLabel: 'Fee POT',
      netLabel: 'Neto distribuido',
      txCounterLabel: 'Transacciones',
      workersCounterLabel: 'Workers activos',
      detailCta: 'Ver detalle de transacciones',
      ctaFromDetail: 'Mi cobro POT',
      footnote: 'El fee POT cubre el procesamiento R4 + dispersión multi-beneficiario.',
    },
    roster: {
      title: tpl('Equipo · {venue}'),
      search: 'Buscar persona',
      add: 'Agregar persona',
      active: 'Activo',
      paused: 'Pausado',
      invite: 'Invitar a tu equipo',
      invitePhone: 'Teléfono',
      inviteRole: 'Rol',
      inviteWeight: 'Peso (%)',
      inviteWeightPlaceholder: '12',
      inviteRoleWaiter: 'Mesero',
      inviteRoleBartender: 'Bartender',
      inviteRoleHost: 'Anfitrión',
      inviteRoleOther: 'Otro',
      inviteWhatsapp: 'Enviar invitación',
      inviteWhatsappTemplate: tpl(
        '¡Hola! Te invito al pote de {venue}. Unite con código {code} en POT.',
      ),
      whatsappMessageLabel: 'Mensaje WhatsApp:',
      whatsappMessageInvite:
        '"¡Hola! Te invito al pote de La Brisa. Únete con código ABC-1234 en POT."',
      maxHint: 'Hasta 30 workers por pote · POC sin límite real',
      staffViewTitle: 'Vista del staff',
      staffViewBody: tpl('Así ve {firstName} su pote'),
      staffViewClose: 'Cerrar',
      staffViewRoleLabel: tpl('{role} · {pct} del pote'),
      staffViewWeek: 'Semana',
      staffViewShare: 'Tu parte',
      staffViewPrivacy:
        'Cada miembro ve su propio rol, peso y estimado. Nunca ve datos de los otros.',
    },
    distribution: {
      previewTitle: 'Preview distribución',
      shiftTotal: 'Total del turno',
      shiftPeople: tpl('{count} personas'),
      hoursLabel: tpl('{count} horas'),
      confirmPay: 'Confirmar y empezar a pagar',
      executeTitle: 'Ejecutar pagos',
      executeInstructions:
        'Realiza el Pago Móvil desde tu app bancaria. Luego marca aquí como pagado.',
      paid: 'Pagado',
      markPaid: 'Marcar pagado',
      confirmIndividual: 'Confirmar pago',
      confirmPaid: 'Confirmar pagado',
      copyAll: 'Copy all',
      refLabel: 'Referencia Pago Móvil',
      detailTitle: tpl('Turno · {date}'),
      detailRuleApplied: 'Regla aplicada',
      detailSnapshotSaved: 'Snapshot guardado',
      detailHistoryTitle: 'Distribuciones',
      detailMembersCount: tpl('{count} miembros'),
      exportPdf: 'Exportar PDF',
    },
    reports: {
      inflowsTitle: tpl('Inflows · {venue}'),
      distributionsTitle: 'Distribuciones',
      exportTitle: 'Exportar CSV',
      exportRange: 'Rango de fechas',
      exportPotes: 'Potes',
      exportPotesAll: 'Todos',
      exportFields: 'Campos',
      exportFieldDate: 'Fecha',
      exportFieldAmount: 'Monto',
      exportFieldBank: 'Banco emisor',
      exportFieldRef: 'Referencia R4',
      exportFieldWorker: 'Worker',
      exportFieldPote: 'Pote',
      generate: 'Generar CSV',
    },
    config: {
      title: 'Configuración',
      dataSection: 'Datos del comercio',
      accountSection: 'Cuenta destino',
      deleteCommerce: 'Eliminar comercio',
      editLegalName: 'Editar razón social',
      editRif: 'Editar RIF',
      editAddress: 'Editar dirección',
      changeBank: 'Cambiar banco (re-OTP)',
      changePagoMovil: 'Cambiar Pago Móvil (re-OTP)',
      kycRejectedTitle: 'No pudimos verificar tu comercio',
      kycRejectedBody:
        'Razón: el registro mercantil subido no coincide con el RIF declarado. Verificá y volvé a subir.',
      kycResubmit: 'Volver a enviar documentos',
    },
  },
  consumer: {
    tipping: {
      cta: tpl('Dale propina a {firstName}'),
      amountTitle: 'Monto',
      amountOther: 'Otro monto',
      sharedPotePrompt: '¿Pote compartido? Elegí %',
      customAmountTitle: 'Otro monto',
      customAmountLabel: 'Propina',
      customAmountSwitchBs: 'Bs',
      customAmountSwitchUsd: 'USD',
      messageTitle: '¿Algo más?',
      messageBody: tpl('Un mensaje cortico pa {firstName} (opcional).'),
      messagePlaceholder: "Pa' la torta, vale 💚",
      messageSkip: 'Saltar',
      confirmTitle: 'Confirmar',
      confirmTo: 'A',
      confirmAmount: 'Monto',
      confirmMessage: 'Mensaje',
      confirmMethod: 'Método',
      confirmMethodValue: 'Débito Inmediato',
      confirmDisclaimer: 'Esta propina es voluntaria y adicional al 10% del local.',
      confirmTipLabel: 'Propina para',
      confirmTipAmountLabel: 'Propina',
      confirmTotalLabel: 'Total a pagar',
      confirmServiceDisclosure: 'El monto incluye servicio de pasarela POT',
      confirmMessageLabel: 'Tu mensaje',
      payCtaTotal: tpl('Pagar {amount}'),
      payCta: 'Pagar con Débito Inmediato',
      bankPickerTitle: 'Tu banco',
      bankPickerBody: 'Seleccioná el banco emisor del pago.',
      debitoTitle: 'Débito Inmediato',
      debitoIntro: 'Genera la clave en tu banco y pégala aquí.',
      debitoStep1: 'Abrí tu app bancaria',
      debitoStep2: 'Generá la clave de 8 dígitos',
      debitoStep3: 'Volvé y pegala abajo',
      debitoKeyLabel: 'Clave de 8 dígitos',
      debitoSafety: '🔒 La clave expira en 2 minutos. Tu dinero va directo al Pago Móvil.',
      debitoConfirm: 'Confirmar pago',
      processingTitle: 'Procesando tu propina',
      processingBody: 'Esto tarda menos de 10 segundos.',
      processingStep1: 'Validando con tu banco',
      processingStep2: 'Procesando dispersión',
      processingStep3: 'Generando comprobante',
      successTitle: '¡Listo!',
      successBody: tpl('{firstName} ya recibió tu propina'),
      successTip: 'Propina',
      successRef: 'Referencia',
      successDate: 'Fecha',
      successValidatedBy: 'Validado por',
      successWhatsapp: 'Recibir comprobante por WhatsApp',
      successShare: 'Compartir',
      successDone: 'Listo',
      potPublicReceived: 'Recibió',
      potPublicAnonRef: 'Referencia anonimizada',
      potPublicShareBody: 'Cada PoT es un comprobante verificable. Compartilo donde quieras.',
      potPublicShare: 'Compartir PoT',
      errorTitle: 'No pudimos procesar',
      errorBody:
        'La clave de 8 dígitos no fue aceptada por tu banco. Suele expirar tras 2 minutos.',
      errorOtherBank: 'Usar otro banco',
      qrInvalidTitle: 'Este QR ya no sirve',
      qrInvalidBody:
        'El trabajador puede haberse desactivado o haber actualizado su QR. Pedí uno nuevo en el local.',
      qrInvalidBack: 'Volver',
      qrInvalidClose: 'Cerrar',
      feeAboutLink: '¿Qué es POT?',
      feeAboutTitle: '¿Qué es POT?',
      feeAboutBody:
        'POT es la pasarela que conecta tu pago al banco del trabajador. El servicio cubre el procesamiento R4 y la dispersión instantánea. El trabajador recibe la propina íntegra en su cuenta.',
      feeAboutClose: 'Listo',
    },
  },
  admin: {
    login: {
      title: 'POT · Admin',
      subtitle: 'Solariis team only',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      twoFaLabel: 'Código 2FA',
      enter: 'Entrar',
      footer: 'Acceso restringido. Toda actividad queda auditada.',
    },
    dashboard: {
      title: 'Dashboard',
      brandLine: 'Admin · POT',
      txProcessed: 'TX procesadas (hoy)',
      gmv: 'GMV (USD)',
      activeWorkers: 'Workers activos',
      verifiedCommerces: 'Comercios verificados',
      potFeeRevenue: 'Fee POT revenue (hoy)',
      potFeeRevenueDeltaPositive: tpl('+{pct}% vs ayer'),
      txPerHour: 'TX por hora · últimas 24h',
      successRate: 'Success rate',
      r4Latency: 'Latencia R4 promedio',
      r4LatencyValue: tpl('Latencia R4 promedio: {latency}'),
      alertsActive: 'Alertas activas',
      alerts: 'alertas',
      alertsBadge: tpl('{count} alertas'),
      alertBlockedCompliance: '1 comercio bloqueado por compliance · 2h',
      alertPotPending: '4 PoT con regeneración pendiente',
      alertReconcilDelta: 'Reconciliación R4 con discrepancia · Bs 12,50',
      alertActionResolve: 'Resolver →',
    },
    lookup: {
      usersTitle: 'Lookup users',
      usersBody: 'Buscar workers por teléfono, cédula, o referencia.',
      usersPlaceholder: 'teléfono, cédula, o ref ····',
      colWorker: 'Worker',
      colCedula: 'Cédula',
      colPhone: 'Teléfono',
      colStatus: 'Status',
      colTipsCount: '# tips',
      statusActive: 'Activo',
      statusPaused: 'Pausado',
      txTitle: 'Lookup transactions',
      txColRef: 'Ref',
      txColDate: 'Fecha',
      txColFrom: 'De',
      txColTo: 'Para',
      txColAmount: 'Monto',
      txColStatus: 'Status',
      txStatusOk: 'OK',
      txStatusFailed: 'Failed',
      txPaginationLabel: tpl('{count} de {total} tx'),
      filters: 'Filtros',
    },
    userDetail: {
      title: 'Admin · Worker',
      statusActive: 'Activa',
      tipsTotal: 'Tips totales',
      gmv: 'GMV',
      since: 'Desde',
      actionsLabel: 'Acciones',
      pause: 'Pausar',
      changeAccount: 'Cambiar cuenta',
      resetOtp: 'Reset OTP',
      lastTransactions: 'Últimas transacciones',
      viewActivityLog: 'Ver activity log →',
    },
    txDetail: {
      brandLine: 'Transaction',
      statusLabel: 'Status',
      statusValidated: 'Validada por R4',
      latencyLabel: tpl('Latencia: {latency}'),
      auditTrail: 'Audit trail',
      auditStarted: 'Iniciada',
      auditValidated: 'Validada banco emisor',
      auditWebhook: 'R4 webhook',
      auditDispersion: 'Dispersión completada',
      auditPotGenerated: 'PoT generado',
      r4Payload: 'Webhook R4 payload',
      regeneratePoT: 'Regenerar PoT',
      openPublic: 'Abrir PoT pública',
    },
    kyc: {
      queueTitle: 'Cola de verificación',
      queueBody: tpl('{count} comercios esperando KYC'),
      queueWaitingLabel: tpl('{rif} · esperando {waiting}'),
      priorityHigh: 'high',
      priorityMedium: 'medium',
      priorityLow: 'low',
      sla: 'SLA < 24h',
      reviewVerify: 'Verificar',
      reviewReject: 'Rechazar (razón requerida)',
      declaredData: 'Datos declarados',
      declaredLegalName: 'Razón social',
      declaredRif: 'RIF',
      declaredSector: 'Sector',
      declaredAddress: 'Dirección',
      declaredResponsible: 'Responsable',
      declaredDestAccount: 'Cuenta destino',
      docPreview: 'Registro mercantil',
    },
    reconciliation: {
      title: 'Reconciliación R4',
      subtitle: 'Diaria · auto-corre 00:30 UTC',
      colDay: 'Día',
      potCol: 'POT',
      r4Col: 'R4',
      deltaCol: 'Δ',
      colStatus: 'Status',
      statusOk: 'OK',
      statusOpen: 'Abierta',
      investigate: 'Investigar',
      resolve: 'Resolver',
      openCount: tpl('{count} abierta(s)'),
      openBadge: tpl('{count} abierta'),
      resolveReasonTitle: 'Razón de resolución',
      resolveReasonHint: 'Audit trail — campo obligatorio.',
      resolveReasonPlaceholder: 'Describe brevemente cómo se resolvió la discrepancia…',
      resolveReasonPreset1: 'Ajuste manual en R4',
      resolveReasonPreset2: 'Tx duplicada — corregida',
      resolveReasonPreset3: 'Diferencia tipo de cambio',
      resolveReasonPreset4: 'Webhook reprocessed',
      resolveReasonSubmit: 'Marcar resuelta',
      resolveReasonCancel: 'Cancelar',
    },
    health: {
      title: 'Logs / Health',
      r4Operational: 'R4 operational',
      pushOk: 'Push OK',
      webhooks24h: 'Webhooks R4 (24h)',
      apiErrors24h: 'API errors (24h)',
      pushDeliveryRate: 'Push delivery rate',
      recentActivity: 'Recent activity',
      withinSlo: 'within SLO',
      attention: 'attention',
      filtersLabel: 'Filtros',
      clearFilters: 'Limpiar filtros',
      filterChipSource: 'R4 webhook',
      filterChipStatus: 'Errors only',
    },
  },
  shared: {
    common: {
      yes: 'Sí',
      no: 'No',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      retry: 'Reintentar',
      back: 'Volver',
      next: 'Siguiente',
      continue: 'Continuar',
      skip: 'Saltar',
      save: 'Guardar',
      done: 'Listo',
      share: 'Compartir',
      download: 'Descargar',
      edit: 'Editar',
      delete: 'Eliminar',
      close: 'Cerrar',
      search: 'Buscar',
      stepOf: ({ current, total }: { current: number; total: number }) =>
        `Paso ${current} de ${total}`,
    },
    errors: {
      generic: 'Algo salió mal',
      retry: 'Volvé a intentar',
      network: 'Sin conexión. Probá de nuevo.',
      r4Unavailable: 'Servicio temporalmente no disponible',
      invalidOtp: 'El código no coincide',
      badKey: 'Clave inválida',
      expired: 'La clave expiró',
      noFunds: 'Fondos insuficientes',
    },
    money: {
      bs: 'Bs',
      usd: 'USD',
      bsApprox: (bs: string, usd: string) => `Bs ${bs} · ≈ ${usd} USD`,
    },
    splash: {
      brandTag: 'Pagos Oportunos y Transparentes',
      brandTagCommerce: 'POT · Negocio',
    },
    identity: {
      entityType: {
        labelDestino: 'Destino del pago',
        natural: 'Natural',
        juridico: 'Jurídico',
      },
      prefixes: {
        natural: {
          V: 'V - Venezolano',
          E: 'E - Extranjero',
          P: 'P - Pasaporte',
        },
        juridico: {
          J: 'J - Jurídico privado',
          V: 'V - Natural con RIF',
          E: 'E - Extranjera con RIF',
          G: 'G - Gobierno',
          C: 'C - Consejos comunales',
        },
      },
      prefixSelectorAria: 'Seleccionar prefijo de identidad',
      fieldLabels: {
        cedula: 'Cédula',
        rif: 'RIF',
      },
      placeholders: {
        cedula: '12.345.678',
        rif: '12345678-9',
      },
    },
    brand: {
      tagline: 'Pagos Oportunos y Transparentes',
    },
    transversales: {
      pushPrePrimingTitle: '¿Te avisamos?',
      pushPrePrimingBody:
        'Vamos a pedirte permiso para enviarte avisos cuando llegue una propina. Lo apagás cuando quieras.',
      pushPrePrimingYes: 'Sí, avísame',
      cameraPrePrimingTitle: 'Permití la cámara',
      cameraPrePrimingBody:
        'Para escanear el QR del local. Solo la usamos al escanear, nunca de fondo.',
      cameraPrePrimingYes: 'Permitir cámara',
      updateTitle: 'Hay una nueva versión',
      updateBody: 'Actualizá POT para seguir recibiendo propinas. Toma menos de un minuto.',
      updateCta: 'Actualizar ahora',
      maintenanceTitle: 'Estamos mejorando POT',
      maintenanceBody: 'Te avisamos cuando termine. No vas a perder ninguna propina.',
      maintenanceEta: 'Volvemos en ~15 minutos',
      pushPrePrimingBodyAlt:
        'Vamos a pedirte permiso para enviarte avisos cuando llegue una propina. Puedes apagarlos cuando quieras.',
      cameraPrePrimingTitleAlt: 'Permite la cámara',
      cameraPrePrimingYesAlt: 'Permitir cámara',
      updateBodyAlt: 'Actualiza POT para seguir recibiendo propinas. Toma menos de un minuto.',
      errorModalTitle: 'Algo salió mal',
      errorModalBody: 'No pudimos completar tu solicitud. Vuelve a intentar en unos segundos.',
    },
  },
} as const;

export default microcopy;
export { microcopy };
