/**
 * Re-exports of domain types from `@solariis-com/pot-types` plus client-local
 * types that aren't appropriate for the shared types package (e.g. wire
 * envelopes, transport DTOs).
 *
 * The re-export indirection lets consumers do
 *   `import { Pote, PoteCreateInput } from '@solariis-com/pot-api-client';`
 * without also adding `@solariis-com/pot-types` to their dependency list.
 */
export type {
  Pote,
  PoteLifecycle,
  PoteIntegrante,
  PoteKind,
  DistributionRule,
  DistributionRuleKind,
  MVPDistributionRuleKind,
  BeneficiarySplit,
  User,
  UserRole,
  Worker,
  Commerce,
  Consumer,
  Admin,
  WorkerType,
  AccountStatus,
  BankAccount,
  IdentityDocument,
  NaturalIdentity,
  JuridicoIdentity,
  EntityType,
} from '@solariis-com/pot-types';

// ---- Client-local transport types (NOT domain — wire envelopes only) ----

/** Generic paginated list envelope. */
export interface Paginated<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}

/** Cursor-paginated envelope, for transaction history and long lists. */
export interface CursorPaginated<T> {
  items: T[];
  nextCursor: string | null;
}

/** Standard list query options. */
export interface ListQuery {
  page?: number;
  pageSize?: number;
  /** Free-text search; backend interprets per resource. */
  q?: string;
}

/** Cursor-based query for transaction history. */
export interface CursorQuery {
  cursor?: string;
  limit?: number;
}

/**
 * Per-request override knobs. `requiresAuth: false` lets the OTP request
 * endpoint skip Bearer injection; idempotency-key is auto-generated by the
 * retry-interceptor on POSTs unless the caller provides one.
 */
export interface RequestOptions {
  requiresAuth?: boolean;
  idempotencyKey?: string;
  /** Per-request timeout override (ms). */
  timeoutMs?: number;
  /** Optional AbortSignal for cancellation. */
  signal?: AbortSignal;
}
